image: archlinux
packages:
  - go
  - git
secrets:
  - dfbc7cb0-b02f-44ab-9b11-cf1a5467c3d2
sources:
  - ssh://git@git.jba.io:go/auth.git
environment:
  project: auth
triggers:
  - action: email
    condition: failure
    to: Jordan Anderson <jordan@jba.io>
tasks:
  - setup: |
      cd ${project}
      go get -d
  - test: |
      cd ${project}
      go test
      go test -cover
      go test -bench=.
