// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User_Role int32

const (
	User_USER  User_Role = 0
	User_ADMIN User_Role = 1
)

var User_Role_name = map[int32]string{
	0: "USER",
	1: "ADMIN",
}
var User_Role_value = map[string]int32{
	"USER":  0,
	"ADMIN": 1,
}

func (x User_Role) String() string {
	return proto.EnumName(User_Role_name, int32(x))
}
func (User_Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type User struct {
	Name     string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password []byte    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role     User_Role `protobuf:"varint,3,opt,name=role,enum=auth.User_Role" json:"role,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *User) GetRole() User_Role {
	if m != nil {
		return m.Role
	}
	return User_USER
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterEnum("auth.User_Role", User_Role_name, User_Role_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x2d, 0xc9, 0x50, 0xaa, 0xe0, 0x62,
	0x09, 0x2d, 0x4e, 0x2d, 0x12, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xa4, 0xb8, 0x38, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b,
	0x52, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xe0, 0x7c, 0x21, 0x65, 0x2e, 0x96, 0xa2, 0xfc,
	0x9c, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x7e, 0x3d, 0x90, 0x61, 0x7a, 0x20, 0x93,
	0xf4, 0x82, 0xf2, 0x73, 0x52, 0x83, 0xc0, 0x92, 0x4a, 0xd2, 0x5c, 0x2c, 0x20, 0x9e, 0x10, 0x07,
	0x17, 0x4b, 0x68, 0xb0, 0x6b, 0x90, 0x00, 0x83, 0x10, 0x27, 0x17, 0xab, 0xa3, 0x8b, 0xaf, 0xa7,
	0x9f, 0x00, 0x63, 0x12, 0x1b, 0xd8, 0x19, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xb8,
	0xe0, 0xd3, 0x94, 0x00, 0x00, 0x00,
}
